name: Deploy and Run Tests

on:
  push:
    branches:
      - main  # Заміни на вашу основну гілку, якщо вона має іншу назву
  pull_request:
    branches:
      - main  # Заміни на вашу основну гілку

jobs:
  build:
    runs-on: ubuntu-latest  # Ви можете використовувати інші платформи, якщо потрібно

    steps:
    # 1. Клонування репозиторію
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Налаштування Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Заміни на потрібну версію Python

    # 3. Встановлення залежностей
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Запуск тестів
    - name: Run tests
      run: |
        python -m unittest discover -s tests  # Якщо ваші тести знаходяться в папці tests
