name: Build EXE with PyInstaller

on:  [push]

jobs:
  build:
    runs-on: windows-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: pyinstaller --onefile --icon=picture.ico --add-data=expenses:expenses --add-data=income:income --add-data=savings:savings --add-data=settings:settings main.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: Project_EXE
          path: dist/main.exe

