name: Deploy and Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Xvfb
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        export DISPLAY=:99.0
        nohup Xvfb :99 -screen 0 1280x1024x24 &

    - name: Run tests
      run: |
        python -m unittest discover -s tests
